# Generated by Django 5.1.4 on 2025-03-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='location',
        ),
        migrations.AddField(
            model_name='hotel',
            name='address',
            field=models.TextField(default='Default Address'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(upload_to='hotel_images/'),
        ),
    ]
