# Generated by Django 5.1.4 on 2025-04-10 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0005_contactmessage_remove_booking_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name_plural': 'Hotels'},
        ),
    ]
