# Generated by Django 5.1.4 on 2025-04-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0006_alter_hotel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
