# Generated by Django 5.1.4 on 2025-04-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0007_hotel_city_alter_hotel_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
