# Generated by Django 5.1.4 on 2025-04-14 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0008_hotel_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={},
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='images',
        ),
    ]
