# Generated by Django 5.1.4 on 2025-04-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0009_alter_hotel_options_remove_hotel_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='default',
            field=models.BooleanField(default=True),
        ),
    ]
