# Generated by Django 5.1.4 on 2025-04-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0010_hotel_images_alter_hotel_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name_plural': 'Hotels'},
        ),
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
