# Generated by Django 5.1.4 on 2025-04-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0011_alter_hotel_options_hotel_amenities_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='default',
            new_name='is_default',
        ),
        migrations.AddField(
            model_name='hotel',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
