# Generated by Django 5.1.4 on 2025-04-16 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0012_rename_default_hotel_is_default_hotel_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='is_default',
            new_name='default',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='location',
        ),
    ]
