# Generated by Django 5.1.4 on 2025-04-17 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0013_rename_is_default_hotel_default_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='images',
            new_name='image_paths',
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.ImageField(upload_to='hotel_images/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='booking_app.hotel')),
            ],
        ),
    ]
