# Generated by Django 5.1.4 on 2025-04-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0014_rename_images_hotel_image_paths_hotelimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='image_paths',
            new_name='images',
        ),
        migrations.DeleteModel(
            name='HotelImage',
        ),
    ]
