# Generated by Django 5.1.4 on 2025-04-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0015_rename_image_paths_hotel_images_delete_hotelimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='default',
            field=models.BooleanField(default=True),
        ),
    ]
