# Generated by Django 5.1.4 on 2025-04-21 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0018_booking_feedback_submitted_booking_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='comment',
        ),
        migrations.AddField(
            model_name='feedback',
            name='booking',
            field=models.ForeignKey(default='6', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='booking_app.booking'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
    ]
