# Generated by Django 5.1.4 on 2025-04-24 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0020_remove_booking_feedback_submitted_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='manager',
        ),
    ]
