# Generated by Django 5.1.4 on 2025-04-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0021_delete_room_remove_hotel_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='number_of_rooms',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
