# Generated by Django 5.1.4 on 2025-05-01 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0023_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
