# Generated by Django 5.1.4 on 2025-04-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0019_remove_feedback_comment_feedback_booking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='feedback_submitted',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='comments',
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')]),
        ),
    ]
